dataset: fashion_mnist
batch_size: 20
epochs: 1000
lr: 0.1
gamma: 0.5  # Learning rate decay
step_size: 10  # Learning rate decay step
seed: 123
verbose: false
test_every_epoch: true
weight_folder: ../data/fp_weights/${dataset}/